import {RESTAURANTS} from '../assets';
 
 async function fetchRestaurants() {
    return [
        {
            img: RESTAURANTS.claro,
            name: 'Claro',
            chef: 'Ram Shmueli',
            opening_hour: 7,
            closing_hour: 11,
            new: true,
            popular: true,
        },
        {
            img: RESTAURANTS.kab_kem,
            name: 'Kab Kem',
            chef: 'Yariv Malili',
            opening_hour: 7,
            closing_hour: 18,
            new: true,
            popular: true,
        },
        {
            img: RESTAURANTS.messa,
            name: 'Messa',
            chef: 'Aviv Moshe',
            opening_hour: 9,
            closing_hour: 23,
            new: true,
            popular: true,
        },
        {
            img: RESTAURANTS.nithan_thai,
            name: 'Nitan Thai',
            chef: 'Shahaf Shabtay',
            opening_hour: 10,
            closing_hour: 23,
            new: false,
            popular: false,
        },
        {
            img: RESTAURANTS.claroso,
            name: 'Claroso',
            chef: 'Rani Shmueli',
            opening_hour: 15,
            closing_hour: 17,
            new: false,
            popular: true,
        },
        {
            img: RESTAURANTS.la_kemno,
            name: 'La Kemno',
            chef: 'Yariv Mali',
            opening_hour: 18,
            closing_hour: 22,
            new: false,
            popular: false,
        },
        {
            img: RESTAURANTS.nissan,
            name: 'Nissan',
            chef: 'Aviv Mali',
            opening_hour: 7,
            closing_hour: 23,
            new: false,
            popular: false,
        },
        {
            img: RESTAURANTS.tiger_lily,
            name: 'Tiger Lily',
            chef: 'Yanir Green',
            opening_hour: 14,
            closing_hour: 22,
            new: false,
            popular: false,
        },
        {
            img: RESTAURANTS.yapan,
            name: 'Ya Pan',
            chef: 'Yuval Ben Moshe',
            opening_hour: 10,
            closing_hour: 22,
            new: false,
            popular: true,
        },
    ]
  };
  export default fetchRestaurants;