export {default as CuisinesReducer} from "./CuisinesSlicer";
export {default as dishesReducer} from "./DishesSlicer";
export {default as restaurantsReducer} from "./RestaurantsSlicer";
export {default as chefsReducer} from "./ChefsSlicer";
export {default as TopChefReducer} from "./TopChefSlicer";
export {default as TopChefDishesReducer} from "./TopChefDishesSlicer";
export {default as popularRestaurantsReducer} from "./popularRestaurantsSlicer";
export {default as popularDishesReducer} from "./popularDishesSlicer";
export {default as activeRestaurantReducer} from "./activeRestaurantSlicer";
export {default as activeRestaurant_lanchesReducer} from "./lanchesSlicer";
export {default as activeRestaurant_dinnersReducer} from "./dinnersSlicer";
export {default as activeRestaurant_breakfastsReducer} from "./breakfastsSlicer";
export {default as activeDishReducer} from "./activeDishSlicer";
export {default as changesOnDishReducer} from "./changesOnDishSlicer";
export {default as sideOnDishReducer} from "./sideOnDishSlicer";
export {default as quantityOfDishReducer} from "./quantityOfDishSlicer";
export {default as itemsInBagReducer} from "./itemsInBagSlicer"