export {default as ICONS} from './icons/index'
export {default as IMAGES} from './images/index'
export {default as LINES} from './lines/index'
export {default as BIG_ICONS} from './big_icons/index'
export {default as CHEFS} from './chefs/index'
export {default as RESTAURANTS} from './Restaurants/index'
export {default as DISHES} from './Dishes/index'
